"""Runtime orchestration: shared constants, context, and module wiring."""

from trader.runtime.constants import (
    CRITICAL_TASK_NAMES,
    DIAG_WINDOW,
    FALLBACK_BALANCE_USD,
    INTERVAL_MS,
    JOURNAL_FALLBACK_UUID,
    MIN_SEED_BARS,
    ML_REPLACEMENT_COUNTER,
    STRATEGY_LOOP_INTERVAL,
    SUPERVISOR_CHECK_INTERVAL,
    SUPERVISOR_HEARTBEAT_INTERVAL,
    SYMBOLS,
    TRADE_JOURNAL_RECONNECT_INTERVAL,
    WS_INTERVAL,
)

__all__ = [
    "CRITICAL_TASK_NAMES",
    "DIAG_WINDOW",
    "FALLBACK_BALANCE_USD",
    "INTERVAL_MS",
    "JOURNAL_FALLBACK_UUID",
    "ML_REPLACEMENT_COUNTER",
    "MIN_SEED_BARS",
    "STRATEGY_LOOP_INTERVAL",
    "SUPERVISOR_CHECK_INTERVAL",
    "SUPERVISOR_HEARTBEAT_INTERVAL",
    "SYMBOLS",
    "TRADE_JOURNAL_RECONNECT_INTERVAL",
    "WS_INTERVAL",
]
