"""Domain models for the Bybit AI trading system.

All models use Pydantic v2.  Immutable models use ``frozen=True``.
"""

from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)

from trader.domain.enums import (
    MarketRegime,
    MarketType,
    OrderSide,
    OrderType,
    RiskDecisionStatus,
    SystemStatus,
    TradingMode,
    VolatilityLevel,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ORDER_LINK_ID_RE = re.compile(r"^[a-zA-Z0-9_-]{1,36}$")


def _now_utc() -> datetime:
    return datetime.now(tz=UTC)


# ---------------------------------------------------------------------------
# Market data models
# ---------------------------------------------------------------------------


class MarketEvent(BaseModel):
    """Raw market data snapshot received from the exchange."""

    model_config = ConfigDict(frozen=True)

    event_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    symbol: str = Field(..., min_length=1, max_length=32)
    market_type: MarketType
    timestamp: datetime = Field(default_factory=_now_utc)
    received_at: datetime = Field(default_factory=_now_utc)

    # OHLCV fields (optional — may not be present in order-book events)
    open: Decimal | None = None
    high: Decimal | None = None
    low: Decimal | None = None
    close: Decimal | None = None
    volume: Decimal | None = None
    turnover: Decimal | None = None

    # Best bid / ask
    bid: Decimal | None = None
    ask: Decimal | None = None
    bid_size: Decimal | None = None
    ask_size: Decimal | None = None

    # Mark / index price (derivatives)
    mark_price: Decimal | None = None
    index_price: Decimal | None = None
    funding_rate: Decimal | None = None

    # Data quality
    latency_ms: float | None = None
    source: str = "websocket"

    @field_validator("symbol")
    @classmethod
    def symbol_uppercase(cls, v: str) -> str:
        return v.upper()

    @field_validator("latency_ms")
    @classmethod
    def latency_non_negative(cls, v: float | None) -> float | None:
        if v is not None and v < 0:
            raise ValueError("latency_ms must be non-negative")
        return v


class FeatureVector(BaseModel):
    """Computed feature vector ready for model inference."""

    model_config = ConfigDict(frozen=True)

    feature_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    symbol: str
    timestamp: datetime = Field(default_factory=_now_utc)

    # Numerical features (ordered; length must match model's input dim)
    values: list[float] = Field(..., min_length=1)

    # Named feature map (for interpretability / logging)
    feature_names: list[str] = Field(default_factory=list)

    # Quality indicator [0, 1]
    quality_score: float = Field(..., ge=0.0, le=1.0)

    # How many raw data points fed into this vector
    lookback_bars: int = Field(..., ge=1)

    # Feature set version (bump on schema changes)
    version: str = "v1"

    @model_validator(mode="after")
    def names_length_matches(self) -> FeatureVector:
        if self.feature_names and len(self.feature_names) != len(self.values):
            raise ValueError(
                f"feature_names length ({len(self.feature_names)}) must match values length ({len(self.values)})"
            )
        return self


class RegimeContext(BaseModel):
    """Detected market regime and associated metadata."""

    model_config = ConfigDict(frozen=True)

    context_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    symbol: str
    timestamp: datetime = Field(default_factory=_now_utc)

    regime: MarketRegime
    volatility_level: VolatilityLevel
    confidence: float = Field(..., ge=0.0, le=1.0)

    # Supporting statistics
    realized_vol_1h: float | None = None
    realized_vol_24h: float | None = None
    spread_bps: float | None = None
    depth_imbalance: float | None = None

    # Regime allowed for trading?
    trading_allowed: bool = True
    block_reason: str | None = None


# ---------------------------------------------------------------------------
# Trade proposal / risk models
# ---------------------------------------------------------------------------


class TradeProposal(BaseModel):
    """Signal generated by a strategy or RL model requesting a trade."""

    model_config = ConfigDict(frozen=True)

    proposal_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    strategy_id: str = Field(..., min_length=1, max_length=64)
    symbol: str
    market_type: MarketType
    side: OrderSide
    timestamp: datetime = Field(default_factory=_now_utc)

    # Sizing
    requested_qty: Decimal = Field(..., gt=Decimal(0))
    requested_notional_usd: Decimal | None = None

    # Price targets
    entry_price: Decimal | None = None  # None → market order
    take_profit: Decimal | None = None
    stop_loss: Decimal | None = None

    # Model confidence [0, 1]
    confidence: float = Field(..., ge=0.0, le=1.0)

    # Risk / reward estimate
    expected_return: float | None = None
    expected_risk: float | None = None

    # Regime at time of proposal
    regime: MarketRegime = MarketRegime.UNCERTAIN

    # Feature vector that drove this proposal
    feature_id: uuid.UUID | None = None

    # Human-readable rationale
    rationale: str = ""

    @field_validator("symbol")
    @classmethod
    def symbol_uppercase(cls, v: str) -> str:
        return v.upper()

    @model_validator(mode="after")
    def sl_on_correct_side(self) -> TradeProposal:
        if self.stop_loss is not None and self.entry_price is not None:
            if self.side == OrderSide.BUY and self.stop_loss >= self.entry_price:
                raise ValueError("stop_loss must be below entry_price for BUY")
            if self.side == OrderSide.SELL and self.stop_loss <= self.entry_price:
                raise ValueError("stop_loss must be above entry_price for SELL")
        return self


class RiskDecision(BaseModel):
    """Risk Manager's verdict on a TradeProposal."""

    model_config = ConfigDict(frozen=True)

    decision_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    proposal_id: uuid.UUID
    timestamp: datetime = Field(default_factory=_now_utc)

    status: RiskDecisionStatus

    # Approved quantity (may differ from requested)
    approved_qty: Decimal | None = None
    approved_notional_usd: Decimal | None = None

    # If RESIZED, original requested qty
    original_qty: Decimal | None = None

    # Human-readable reason (especially on REJECTED)
    reason: str = ""

    # Which risk rule triggered the decision
    triggered_rules: list[str] = Field(default_factory=list)

    # Portfolio-level metrics at time of decision
    portfolio_heat: float | None = None
    current_drawdown_pct: float | None = None
    open_positions_count: int | None = None

    @model_validator(mode="after")
    def approved_qty_required_when_approved(self) -> RiskDecision:
        if self.status in (RiskDecisionStatus.APPROVED, RiskDecisionStatus.RESIZED):
            if self.approved_qty is None:
                raise ValueError("approved_qty is required when status is APPROVED or RESIZED")
            if self.approved_qty <= 0:
                raise ValueError("approved_qty must be positive")
        return self


# ---------------------------------------------------------------------------
# Order models
# ---------------------------------------------------------------------------


class OrderIntent(BaseModel):
    """Fully-specified order parameters ready for submission to the exchange."""

    model_config = ConfigDict(frozen=True)

    intent_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    decision_id: uuid.UUID
    proposal_id: uuid.UUID

    # Bybit-specific fields
    symbol: str
    market_type: MarketType
    side: OrderSide
    order_type: OrderType

    qty: Decimal = Field(..., gt=Decimal(0))
    price: Decimal | None = None  # Required for LIMIT

    # Idempotency key sent to exchange (max 36 chars, alphanumeric + _-)
    order_link_id: str = Field(..., min_length=1, max_length=36)

    # Risk management orders
    take_profit: Decimal | None = None
    stop_loss: Decimal | None = None
    tp_order_type: OrderType = OrderType.LIMIT
    sl_order_type: OrderType = OrderType.MARKET

    # Reduce-only flag
    reduce_only: bool = False

    # Time-in-force (GTC, IOC, FOK, PostOnly)
    time_in_force: str = "GTC"

    created_at: datetime = Field(default_factory=_now_utc)

    @field_validator("order_link_id")
    @classmethod
    def validate_order_link_id(cls, v: str) -> str:
        if not _ORDER_LINK_ID_RE.match(v):
            raise ValueError("order_link_id must be 1-36 alphanumeric chars (plus _ and -)")
        return v

    @model_validator(mode="after")
    def price_required_for_limit(self) -> OrderIntent:
        if self.order_type == OrderType.LIMIT and self.price is None:
            raise ValueError("price is required for LIMIT orders")
        return self


# ---------------------------------------------------------------------------
# Position / balance models
# ---------------------------------------------------------------------------


class Position(BaseModel):
    """Current state of an open position."""

    model_config = ConfigDict(frozen=True)

    position_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    symbol: str
    market_type: MarketType
    side: OrderSide

    size: Decimal
    entry_price: Decimal
    mark_price: Decimal | None = None
    liquidation_price: Decimal | None = None

    unrealised_pnl: Decimal = Decimal(0)
    realised_pnl: Decimal = Decimal(0)
    leverage: Decimal = Decimal(1)
    margin_type: str = "cross"

    opened_at: datetime = Field(default_factory=_now_utc)
    updated_at: datetime = Field(default_factory=_now_utc)

    @field_validator("size")
    @classmethod
    def size_non_negative(cls, v: Decimal) -> Decimal:
        if v < 0:
            raise ValueError("size must be non-negative")
        return v


class Balance(BaseModel):
    """Account balance snapshot."""

    model_config = ConfigDict(frozen=True)

    account_type: str  # UNIFIED, CONTRACT, SPOT
    currency: str

    wallet_balance: Decimal
    available_balance: Decimal
    unrealised_pnl: Decimal = Decimal(0)
    margin_balance: Decimal | None = None

    timestamp: datetime = Field(default_factory=_now_utc)


class InstrumentInfo(BaseModel):
    """Static instrument metadata fetched from exchange."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    market_type: MarketType
    base_coin: str
    quote_coin: str

    # Tick / lot constraints
    min_order_qty: Decimal
    max_order_qty: Decimal
    qty_step: Decimal
    tick_size: Decimal
    min_notional: Decimal | None = None

    # Leverage (linear / inverse)
    max_leverage: Decimal | None = None

    # Optional liquidity context, usually 24h turnover in quote currency.
    turnover_24h: Decimal | None = None

    # Trading status
    status: str = "Trading"

    fetched_at: datetime = Field(default_factory=_now_utc)


class Fill(BaseModel):
    """Individual trade fill (execution report)."""

    model_config = ConfigDict(frozen=True)

    fill_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    exchange_exec_id: str
    order_link_id: str
    symbol: str

    side: OrderSide
    qty: Decimal = Field(..., gt=Decimal(0))
    price: Decimal = Field(..., gt=Decimal(0))
    fee: Decimal = Decimal(0)
    fee_currency: str = "USDT"
    is_maker: bool = False

    executed_at: datetime = Field(default_factory=_now_utc)


# ---------------------------------------------------------------------------
# System / ops models
# ---------------------------------------------------------------------------


class ReconciliationResult(BaseModel):
    """Result of a reconciliation pass between local state and exchange state."""

    model_config = ConfigDict(frozen=True)

    run_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    timestamp: datetime = Field(default_factory=_now_utc)

    orders_checked: int = 0
    positions_checked: int = 0
    discrepancies_found: int = 0
    discrepancies_resolved: int = 0
    discrepancies_unresolved: int = 0

    # Orders whose state diverged
    mismatched_order_ids: list[str] = Field(default_factory=list)

    # Human-readable summary
    summary: str = ""
    success: bool = True


class HealthStatus(BaseModel):
    """Aggregated health status of the trading system."""

    model_config = ConfigDict(frozen=True)

    timestamp: datetime = Field(default_factory=_now_utc)
    overall: str  # healthy / degraded / unhealthy

    postgres: bool = False
    redis: bool = False
    bybit_rest: bool = False
    bybit_ws: bool = False
    model_fresh: bool = False
    features_fresh: bool = False

    system_status: SystemStatus = SystemStatus.STOPPED
    trading_mode: TradingMode = TradingMode.TESTNET

    # Per-component latencies (ms)
    postgres_latency_ms: float | None = None
    redis_latency_ms: float | None = None
    bybit_rest_latency_ms: float | None = None

    # Any health check messages
    messages: list[str] = Field(default_factory=list)

    @property
    def is_healthy(self) -> bool:
        return self.overall == "healthy"


class PreflightReport(BaseModel):
    """Report produced by the preflight check sequence."""

    model_config = ConfigDict(frozen=True)

    run_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    timestamp: datetime = Field(default_factory=_now_utc)

    passed: bool
    checks: dict[str, bool] = Field(default_factory=dict)
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    # Populated only on success
    trading_mode: TradingMode | None = None
    allowed_symbols: list[str] = Field(default_factory=list)


class AuditEvent(BaseModel):
    """Immutable audit log entry for every significant system action."""

    model_config = ConfigDict(frozen=True)

    audit_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    timestamp: datetime = Field(default_factory=_now_utc)
    correlation_id: uuid.UUID | None = None

    actor: str  # system component name
    action: str  # verb describing the action
    resource: str  # what was acted upon
    outcome: str  # success / failure / partial

    # Structured payload (no secrets)
    payload: dict[str, Any] = Field(default_factory=dict)

    # Risk / trading context
    trading_mode: TradingMode | None = None
    symbol: str | None = None
    order_link_id: str | None = None


class ModelMetadata(BaseModel):
    """Metadata describing a deployed ML model."""

    model_config = ConfigDict(frozen=True)

    model_id: str
    version: str
    algorithm: str  # e.g. "PPO", "SAC", "XGBoost"
    strategy_id: str

    trained_at: datetime
    deployed_at: datetime = Field(default_factory=_now_utc)

    # Training metrics
    train_sharpe: float | None = None
    val_sharpe: float | None = None
    train_episodes: int | None = None
    train_steps: int | None = None

    # Drift / freshness
    last_inference_at: datetime | None = None
    inference_count: int = 0
    drift_score: float | None = None
    is_stale: bool = False

    # MLflow run reference
    mlflow_run_id: str | None = None
    artifact_uri: str | None = None

    # Feature set this model was trained on
    feature_version: str = "v1"
    input_dim: int | None = None
    output_dim: int | None = None
