#!/usr/bin/env python3
"""Generate .env.example from Settings field definitions.

Run:
    python scripts/gen_env_example.py > .env.example

CI check:
    python scripts/gen_env_example.py | diff - .env.example
"""
from __future__ import annotations

import sys
import types
from typing import Any, get_args, get_origin


def _type_hint(annotation: Any) -> str:
    """Return a readable type hint string."""
    origin = get_origin(annotation)
    if origin is types.UnionType or str(origin) in ("<class 'types.UnionType'>", "typing.Union"):
        args = [a for a in get_args(annotation) if a is not type(None)]
        return " | ".join(str(a.__name__ if hasattr(a, "__name__") else a) for a in args)
    if hasattr(annotation, "__name__"):
        return annotation.__name__
    return str(annotation)


def main() -> None:
    try:
        from trader.config import Settings
    except ImportError as exc:
        print(f"ERROR: could not import trader.config.Settings — {exc}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# Auto-generated by scripts/gen_env_example.py — do not edit manually",
        "# Re-generate with: python scripts/gen_env_example.py > .env.example",
        "",
    ]

    for field_name, field_info in Settings.model_fields.items():
        description = field_info.description or ""
        default = field_info.default
        annotation = field_info.annotation

        if description:
            lines.append(f"# {description}")

        try:
            type_str = _type_hint(annotation)
            lines.append(f"# Type: {type_str}")
        except Exception:
            pass

        default_display = None
        if default is not None and str(default) not in (
            "PydanticUndefined",
            "<class 'pydantic.fields.PydanticUndefined'>",
        ):
            if "SecretStr" in type(default).__name__ or hasattr(default, "get_secret_value"):
                default_display = "***"
            else:
                default_display = str(default)
        if default_display is not None:
            lines.append(f"# Default: {default_display}")

        is_required = field_info.is_required()
        is_secret = annotation is not None and "SecretStr" in str(annotation)

        if is_required:
            lines.append(f"{field_name}=")
        else:
            sample = "your-value-here" if is_secret else (str(default) if default is not None else "")
            lines.append(f"# {field_name}={sample}")

        lines.append("")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
